Repository mikel/mail, pull requests merged in 2022-12, with the labels that each got.

#1487 refactor: Use Ruby 2's __dir__ where possible
  CHANGELOG.rdoc
  Rakefile
  lib/mail/multibyte/unicode.rb
  rakelib/corpus.rake
  spec/environment.rb
  spec/mail/network/delivery_methods/file_delivery_spec.rb
  spec/mail/network_spec.rb
  spec/spec_helper.rb
Labels: More Work Needed

#1510 [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
  lib/mail/body.rb
  lib/mail/field_list.rb
  lib/mail/mail.rb
  lib/mail/network/delivery_methods/file_delivery.rb
  lib/mail/network/delivery_methods/smtp.rb
  lib/mail/network/delivery_methods/smtp_connection.rb
  lib/mail/network/delivery_methods/test_mailer.rb
  lib/mail/network/retriever_methods/base.rb
  lib/mail/network/retriever_methods/imap.rb
  lib/mail/network/retriever_methods/pop3.rb
  lib/mail/part.rb
  spec/mail/elements/envelope_from_element_spec.rb
  spec/mail/encodings/base64_spec.rb
  spec/mail/encodings/quoted_printable_spec.rb
  spec/mail/fields/bcc_field_spec.rb
  spec/mail/fields/cc_field_spec.rb
  spec/mail/fields/comments_field_spec.rb
  spec/mail/fields/content_description_field_spec.rb
  spec/mail/fields/content_id_field_spec.rb
  spec/mail/fields/content_location_field_spec.rb
  spec/mail/fields/in_reply_to_field_spec.rb
  spec/mail/fields/keywords_field_spec.rb
  spec/mail/fields/message_id_field_spec.rb
  spec/mail/fields/mime_version_field_spec.rb
  spec/mail/fields/references_field_spec.rb
  spec/mail/fields/reply_to_field_spec.rb
  spec/mail/fields/resent_bcc_field_spec.rb
  spec/mail/fields/resent_cc_field_spec.rb
  spec/mail/fields/resent_date_field_spec.rb
  spec/mail/fields/resent_from_field_spec.rb
  spec/mail/fields/resent_to_field_spec.rb
  spec/mail/fields/return_path_field_spec.rb
  spec/mail/fields/structured_field_spec.rb
  spec/mail/fields/to_field_spec.rb
  spec/mail/mail_spec.rb
  spec/mail/message_spec.rb
  spec/mail/multipart_report_spec.rb
  spec/mail/network/retriever_methods/test_retriever_spec.rb
Labels: Ready to Merge

#1491 Lazy-load fields and elements
  CHANGELOG.rdoc
  lib/mail.rb
  lib/mail/field.rb
  lib/mail/fields.rb
  lib/mail/fields/bcc_field.rb
  lib/mail/fields/cc_field.rb
  lib/mail/fields/comments_field.rb
  lib/mail/fields/common_address_field.rb
  lib/mail/fields/common_date_field.rb
  lib/mail/fields/common_message_id_field.rb
  lib/mail/fields/content_description_field.rb
  lib/mail/fields/content_disposition_field.rb
  lib/mail/fields/content_id_field.rb
  lib/mail/fields/content_location_field.rb
  lib/mail/fields/content_transfer_encoding_field.rb
  lib/mail/fields/content_type_field.rb
  lib/mail/fields/date_field.rb
  lib/mail/fields/from_field.rb
  lib/mail/fields/in_reply_to_field.rb
  lib/mail/fields/keywords_field.rb
  lib/mail/fields/message_id_field.rb
  lib/mail/fields/mime_version_field.rb
  lib/mail/fields/named_structured_field.rb
  lib/mail/fields/named_unstructured_field.rb
  lib/mail/fields/optional_field.rb
  lib/mail/fields/received_field.rb
  lib/mail/fields/references_field.rb
  lib/mail/fields/reply_to_field.rb
  lib/mail/fields/resent_bcc_field.rb
  lib/mail/fields/resent_cc_field.rb
  lib/mail/fields/resent_date_field.rb
  lib/mail/fields/resent_from_field.rb
  lib/mail/fields/resent_message_id_field.rb
  lib/mail/fields/resent_sender_field.rb
  lib/mail/fields/resent_to_field.rb
  lib/mail/fields/return_path_field.rb
  lib/mail/fields/sender_field.rb
  lib/mail/fields/structured_field.rb
  lib/mail/fields/subject_field.rb
  lib/mail/fields/to_field.rb
  lib/mail/fields/unstructured_field.rb
  spec/mail/field_spec.rb
  spec/mail/fields/common_field_spec.rb
  spec/mail/fields/common_message_id_spec.rb
  spec/mail/fields/parameter_hash_spec.rb
Labels: More Work Needed

#1514 use match?
  CHANGELOG.rdoc
  lib/mail/encodings.rb
  lib/mail/field.rb
  lib/mail/fields/common_address_field.rb
  lib/mail/fields/content_type_field.rb
  lib/mail/message.rb
  lib/mail/multibyte/chars.rb
  lib/mail/smtp_envelope.rb
Labels: More Work Needed

#1511 Handle parsing of LF-only body with separate parts
  .github/workflows/adhoc.yml
  lib/mail/body.rb
  spec/fixtures/emails/attachment_emails/attachment_pdf_non_ascii.eml
  spec/fixtures/emails/attachment_emails/attachment_pdf_non_ascii_lf.eml
  spec/mail/attachments_list_spec.rb
Labels: RSpec, RFC Compliance, Ready to Merge
